- name: Update repositories cache
  become: yes
  apt:
    update_cache: yes

- name: Upgrade existing packages
  become: yes
  apt:
    upgrade: yes

- name: Install npm packages
  become: yes
  apt:
    name: npm

- name: Install node packages
  become: yes
  apt:
    name: nodejs

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    